### ISSUE TITLE
Custom Vaadin Servlet being ignored

### ISSUE THREAD

**Issue by knacht** [vaadin/spring#17]
Hello,

we need to extend the functionality of the SpringVaadinServlet and tried to add the following (like explained int the API): 
`public class CustomVaadinServlet extends SpringVaadinServlet`

but nothing happend and we had always an instance of the SpringVaadinServlet.

I (believe) i tracked the issue down to the following lines: https://github.com/vaadin/spring/blob/master/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfiguration.java#L188-L190

As a workaround, I added the following configuration
``` java
@Configuration
@Import(value =  VaadinServletConfiguration.class)
public class CustomVaadinConfiguration {
	
	private static final Logger LOGGER = LoggerFactory.getLogger(CustomVaadinConfiguration.class);

	@Bean
	public VaadinServlet vaadinServlet() {
		LOGGER.debug("replacing default SpringVaadinService with instance of {}", CustomVaadinServlet.class.getCanonicalName());
		return new CustomVaadinServlet();
	}

}
```

**Comment by mstahv** [comment]
This is fixed in 1.0.0, somebody please close this issue. //cc @samie

**Comment by knacht** [comment]
Thanks, for the Information.

**Comment by khauser** [comment]
I think this is still not fixed. Please try with vaadin 7.7.3 and spring vaadin 1.0.2.
