### ISSUE TITLE
View scope not working as expected

### ISSUE THREAD

**Issue by lorenzobenvenuti** [vaadin/spring#19]
Hi, 

currently the View scope is activated/deactivated using one ViewChangeListener for each BeanStore; in particular a scope is activated/deactivated in the afterViewChange method. This means that:

- In the ViewChangeListener.afterViewChange method the active scope is not deterministic; since the ViewBeanStore adds/removes listeners every time a view is navigated, depending on when application specific listeners are added they could find no view scope active.

- In the View.enter method the scope is not active (for the first navigation) or is related to the previous view. In my opinion this is not the expected behaviour: when the enter method is invoked the beforeViewChange methods have been invoked, the navigation has not been blocked, the Navigator state has been updated and the view can be populated. At this point you want to refer beans of the view you are entering, not the previous.

As I suggested in a Vaadin trac ticket (https://dev.vaadin.com/ticket/18923), a could be subclassing Navigator; or, better, to change the Navigator API in order to have a "beforeEnter" hook of some kind that can be used to activate scopes.

Thank you,

lorenzo

**Comment by kauvj** [comment]
I am facing the same issue. The view scope should be available when enter() method is being executed. Else it is not of much usage. 
My plans to use spring-vaadin addon are postponed till this bug is fixed.

**Comment by hesara** [comment]
I believe this has been addressed by #68. To check and close if addressed.

**Comment by hesara** [comment]
The fix for #68 fires the view activation event which changes the scope just before calling View.enter() as long as the application uses SpringNavigator or a subclass of it. Thus, considering this fixed.

**Comment by azaberlin** [comment]
I have the same problem still occuring with vaadin 8.1.3 / vaadin-spring-boot-starter 2.0.1. 

My view

`@UIScope
@SpringView(name = NotAnnotatedView.VIEW_NAME)
public class NotAnnotatedView extends VerticalLayout implements View ...`

tries to use a simple vaadin-view-based bean, but I get the message "view not active". Navigator class is SpringNavigator.

`@Scope(scopeName="vaadin-view",` proxyMode=ScopedProxyMode.INTERFACES)
@Bean(name="notAnnotatedViewI")
public NotAnnotated notAnnotatedI() {
	System.out.println("notAnnotatedViewI");
	return new NotAnnotatedImpl();
}`

(also tried with other proxy modes and @ViewScope)
